### ISSUE TITLE
Maybe convert to markdown

### ISSUE THREAD

**Issue by Floppy** [carbon-intensity/terms#1]
@alasdairrwbruce this is great, but perhaps we could convert it to markdown so that it can be easily edited/versioned, people can make suggestions etc? It's a nice statement of openness to have your terms of use be subject to community approval and improvement :)

**Comment by alasdairrwbruce** [comment]
I have converted it to markdown. I agree that it would be good to have the community help shape the terms of use. I have added the terms of use into the README.md file. Is that best, or is it best to have the README.md file link to a separate 'terms-of-use.md' file?

**Comment by Floppy** [comment]
No, README.md will be fine I think. No need to overcomplicate it.
